version: '3.8'
services:
  app:
    image: seungwoncode/toollit-server-app:latest
    ports:
      - '4000:4000'
  nginx:
    restart: always
    image: seungwoncode/toollit-server-nginx:latest
    ports:
      - '80:80'
