name: GitHub Actions
run-name: ${{ github.actor }} executed GitHub Actions
on:
  push:
    branches:
      - production

jobs:
  deploy_docker_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: App build and push docker image
        run: |
          docker build -t toollit-server-app .
          docker tag toollit-server-app:latest ${{ secrets.DOCKER_TOOLLIT_SERVER_APP_REPO_URL }}/toollit-server-app:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_TOOLLIT_SERVER_APP_REPO_URL }}/toollit-server-app:latest

      # - name: Nginx build and push docker image
      #   run: |
      #     docker build -t toollit-server-nginx ./nginx
      #     docker tag toollit-server-app:latest ${{ secrets.DOCKER_REPO_URL }}/toollit-server-app:latest
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker push ${{ secrets.DOCKER_REPO_URL }}/toollit-server-app:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            whoami
            ls -al
